name: Deploy to prod environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          username: 'root'
          host: ${{ secrets.SERVER_HOST }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd music-discord-bot-791227668703477770
            git pull
            npm install
            rm -rf dist
            npx tsc
            npx pm2 reload dist/src/index.js --name "music-discord-bot-791227668703477770" || BOT_CHANEL_ID=791227668703477770 DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN_791227668703477770 }} npx pm2 start dist/src/index.js --name "music-discord-bot-791227668703477770"