name: Sequential Deploy to prod environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest

    env:
      BOT_FOLDER: 'music-discord-bot'
      BOT_SCRIPT: 'dist/src/index.js'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Deploy music-discord-bot-615643942888931329 using ssh
        uses: appleboy/ssh-action@master
        env:
          BOT_CHANEL_ID: "615643942888931329"
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN_615643942888931329 }}
        with:
          username: 'root'
          host: ${{ secrets.SERVER_HOST }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            echo "Open folder ${{ env.BOT_FOLDER }}-${{ env.BOT_CHANEL_ID }}/${{ env.BOT_FOLDER }}"
            cd ${{ env.BOT_FOLDER }}-${{ env.BOT_CHANEL_ID }}/${{ env.BOT_FOLDER }}
            git pull
            rm -rf dist
            rm -rf node_modules
            npm install
            npx tsc
            echo "Reload pm2 ${{ env.BOT_SCRIPT }} | ${{ env.BOT_CHANEL_ID }} | ${{ env.BOT_FOLDER }}-${{ env.BOT_CHANEL_ID }}"
            npx pm2 reload ${{ env.BOT_SCRIPT }} --name "${{ env.BOT_FOLDER }}-${{ env.BOT_CHANEL_ID }}" || BOT_CHANEL_ID=${{ env.BOT_CHANEL_ID }} DISCORD_BOT_TOKEN=${{ env.DISCORD_BOT_TOKEN }} npx pm2 start ${{ env.BOT_SCRIPT }} --name "${{ env.BOT_FOLDER }}-${{ env.BOT_CHANEL_ID }}"

      - name: Deploy music-discord-bot-791227668703477770 using ssh
        uses: appleboy/ssh-action@master
        env:
          BOT_CHANEL_ID: "791227668703477770"
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN_791227668703477770 }}
        with:
          username: 'root'
          host: ${{ secrets.SERVER_HOST }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd ${{ env.BOT_FOLDER }}-${{ env.BOT_CHANEL_ID }}/${{ env.BOT_FOLDER }}
            git pull
            rm -rf dist
            rm -rf node_modules
            npm install
            npx tsc
            npx pm2 reload ${{ env.BOT_SCRIPT }} --name "${{ env.BOT_FOLDER }}-${{ env.BOT_CHANEL_ID }}" || BOT_CHANEL_ID=${{ env.BOT_CHANEL_ID }} DISCORD_BOT_TOKEN=${{ env.DISCORD_BOT_TOKEN }} npx pm2 start ${{ env.BOT_SCRIPT }} --name "${{ env.BOT_FOLDER }}-${{ env.BOT_CHANEL_ID }}"

      - name: Deploy music-discord-bot-841323371505385483 using ssh
        uses: appleboy/ssh-action@master
        env:
          BOT_CHANEL_ID: "841323371505385483"
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN_841323371505385483 }}
        with:
          username: 'root'
          host: ${{ secrets.SERVER_HOST }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd ${{ env.BOT_FOLDER }}-${{ env.BOT_CHANEL_ID }}/${{ env.BOT_FOLDER }}
            git pull
            rm -rf dist
            rm -rf node_modules
            npm install
            npx tsc
            npx pm2 reload ${{ env.BOT_SCRIPT }} --name "${{ env.BOT_FOLDER }}-${{ env.BOT_CHANEL_ID }}" || BOT_CHANEL_ID=${{ env.BOT_CHANEL_ID }} DISCORD_BOT_TOKEN=${{ env.DISCORD_BOT_TOKEN }} npx pm2 start ${{ env.BOT_SCRIPT }} --name "${{ env.BOT_FOLDER }}-${{ env.BOT_CHANEL_ID }}"
